# Generated by Django 6.0.4 on 2026-05-26 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap', models.CharField(max_length=25)),
                ('am', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=40)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipodocumentoidentidad')),
            ],
        ),
    ]
