# Generated by Django 6.0.5 on 2026-05-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumentoidentidad',
            name='tipo',
            field=models.CharField(max_length=40),
        ),
    ]
